### ISSUE TITLE
Add parent node for all declarations

### ISSUE THREAD

**Issue by pokey** [wenkokke/tree-sitter-talon#11]
Would make the grammar easier to work with

**Comment by wenkokke** [comment]
What do you mean by parent nodes? A supertype? I've already done that in thé latest version.

**Comment by pokey** [comment]
A node whose children is the set of declaration nodes

**Comment by wenkokke** [comment]
Yes, those are called supertypes by tree-sitter, and I've added one for almost everything—except rules—in version 2.

**Comment by pokey** [comment]
No that's different from super types. I mean an actual node in the parse tree that they all hang off of

**Comment by wenkokke** [comment]
I think you should be able to use supertypes in the tree-sitter queries?

**Comment by wenkokke** [comment]
Or do you mean a node called `declarations` Much like the `matches` node? That I can do.

**Comment by pokey** [comment]
Exactly

**Comment by wenkokke** [comment]
Fixed
