### ISSUE TITLE
Add field name for left- and right-hand side of declarations

### ISSUE THREAD

**Issue by pokey** [wenkokke/tree-sitter-talon#12]
Given all Talon declarations have the form `foo: bar`, it would be nice if there were a consistent field for `foo` and `bar`.  I could see how you might want more specific field names for those, which is fine, but at least having a field name for all of them would make it easer to work with the grammar

**Comment by wenkokke** [comment]
So `left` and `right` for matches, commands, key bindings, and assignments?

**Comment by pokey** [comment]
Maybe? Cc/ @phillco @andreasarvidsson

**Comment by phillco** [comment]
sgtm!

**Comment by AndreasArvidsson** [comment]
Sounds good

**Comment by wenkokke** [comment]
Fixed
