### ISSUE TITLE
Allow multiple hyphens for context header separator

### ISSUE THREAD

**Issue by auscompgeek** [wenkokke/tree-sitter-talon#16]
Apparently Talon supports multiple hyphens to close the context header? See https://github.com/phillco/talon-axkit/pull/36

**Comment by wenkokke** [comment]
This is deprecated, but still supported for the time being, so it makes sense to support it for now.

**Comment by phillco** [comment]
I think I'd be acceptable to just raise an error -- I think aegis has said that `--` is deprecated -- rather than trying to support it. As long as it doesn't break the existing file as it does currently.

**Comment by wenkokke** [comment]
This was fixed a long time ago.
