### ISSUE TITLE
Don't include space in right-hand side of context

### ISSUE THREAD

**Issue by pokey** [wenkokke/tree-sitter-talon#22]
I think something to do with this line:

https://github.com/wenkokke/tree-sitter-talon/blob/af5d7988181edb6bc257939f6eb11df6630b95ff/grammar.js#L65

Basically the `right` field of `match` includes the space after the `:` in eg `tags: user.foo`

**Comment by wenkokke** [comment]
This just requires redefining `implicit_string` from `/.*/` to some regular expressions that excludes leading and trailing spaces.

Maybe `/(\S|\S.+\S)/`?

**Comment by wenkokke** [comment]
Fix the issue in 7b793a7.
