### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by pokey** [wenkokke/tree-sitter-talon#27]
The `dev` branch is currently failing CI, and [requires some cleanup](https://github.com/wenkokke/tree-sitter-talon/pull/23#issuecomment-1612789644). These CI failures and cleanup need to be addressed before we can cut a new release

**Comment by pokey** [comment]
@wenkokke is there anything @AndreasArvidsson or I can do to help?  Maybe if you describe the current problems on `dev`, we could tackle them, as we are about to start relying on this repo for Cursorless talon support (see https://github.com/cursorless-dev/cursorless/pull/1555).  Thanks!

**Comment by wenkokke** [comment]
No, I've made this mess myself, and it's easier to fix than to explain.

I'll fix it now, so you all will be able to actually contribute and help out in the future.

**Comment by wenkokke** [comment]
Done.

**Comment by pokey** [comment]
Awesome thank you! 🙌

**Comment by wenkokke** [comment]
Henceforth contributions are super welcome.
