### ISSUE TITLE
Bad parse for `face`, `gamepad`, and `parrot`

### ISSUE THREAD

**Issue by pokey** [wenkokke/tree-sitter-talon#29]
Input file:

```
gamepad(north): "north"
face(smile): "smile"
parrot(pop): "pop"
```

parse (ignoring the right-hand sides):

```scm
(source_file
 (declarations
  (gamepad_declaration
   left: "gamepad("
  )
  (face_declaration
   left: "face("
  )
  (parrot_declaration
   left: "parrot("
  )
 )
)
```

I'd expect something a bit more like `key_binding_declaration`, where the `left` field points to the everything before the `:`

**Comment by wenkokke** [comment]
Might be a bug in inlining declarations.

**Comment by wenkokke** [comment]
@pokey Could you test whether #29 fixes your problem?

**Comment by pokey** [comment]
Yes, though I'm having the same problem for `_tag_binding` and `_settings_binding`; would be great if those weren't inlined either

**Comment by wenkokke** [comment]
Fixed. Also aliased `key_action` to `key_binding`.

Let me know if you have further trouble.

**Comment by pokey** [comment]
Confirmed fixed; thank you!
