### ISSUE TITLE
More idiomatic parse for `face`, `gamepad`, etc

### ISSUE THREAD

**Issue by pokey** [wenkokke/tree-sitter-talon#31]
In eg https://github.com/wenkokke/tree-sitter-talon/blob/fd202684c693d1b893fe34575209452424cc9909/grammar.js#L213 we get `face(` as a single, anonymous node.  That doesn't feel super idiomatic.  I'd be tempted to instead have a named node for `face`, or at least to have an anonymous node for `face` that is labeled by a field such as `callee` or something.  WDYT?

Fwiw for now we're working around this by [using a regex to shrink the match](https://github.com/cursorless-dev/cursorless/blob/b88aa6cb52f28a3a4865cc8a8820579cdfb486ab/queries/talon.scm#L121) we get from tree-sitter (using our own custom [`#shrink-to-match!` query predicate operator](https://github.com/cursorless-dev/cursorless/blob/b88aa6cb52f28a3a4865cc8a8820579cdfb486ab/packages/cursorless-engine/src/languages/TreeSitterQuery/queryPredicateOperators.ts#L96-L124)), so we're able to work around it, but it's a little bit awkward 😅

**Comment by wenkokke** [comment]
This is essentially the same issue as #21, from the other side.

The issue remains that it is quite difficult to do consistent and reliably correct parsing and error correcting once the grammar becomes a little bit ambiguous.

As always, I am happy to take suggestions and pull requests, but I am afraid that the optimal solution would be to handle differentiating between commands and other types of declarations in the scanner... which involves messing with a hand-coded lexer in bare bones C++.

**Comment by pokey** [comment]
Ah right, so if you don't make `face(` a single token, then it's much harder to match talon's behaviour where `face(` and `face (` parse differently. Makes sense. We can live with this setup; our workaround is fine. Feel free to close, or leave open if you might one day tackle with a more sophisticated lexer
