### ISSUE TITLE
Tests for anonymous nodes

### ISSUE THREAD

**Issue by pokey** [wenkokke/tree-sitter-talon#32]
From what I can tell, anonymous nodes aren't tested, as they're excluded from the snapshot tests in https://github.com/wenkokke/tree-sitter-talon/tree/dev/test/corpus.  Thus, eg #29 was fixed without any altered / added test cases to ensure it doesn't regress. It would be good if there were regression tests for anonymous nodes. Maybe we should look at other tree-sitter repos to see if anyone has an easy / idiomatic way to do this

**Comment by wenkokke** [comment]
I'm happy to range suggestions and PRs. You're right that it's difficult. Back when I wrote the bulk of this, it seemed that testing the wasm was already above and beyond.

Maybe it's possible to extract something from the Cursorless code and test cases? We'd basically need to implement a small testing framework using the actual tree sitter API.

**Comment by wenkokke** [comment]
Wait, what exactly would you like? The point of anonymous nodes is that they're not in the tree, so we cannot test for them.

**Comment by wenkokke** [comment]
Are you wanting to test that these nodes remain named and in the tree? Because that's currently tested.

**Comment by wenkokke** [comment]
Closing this because anonymous nodes cannot be tested for, and the names nodes in question are tested for already.
