### ISSUE TITLE
Parser fails on implicit strings of two characters

### ISSUE THREAD

**Issue by AndreasArvidsson** [wenkokke/tree-sitter-talon#34]
Below generates an error node. If I rename the language key to something else it works.

```talon
language: en
-

foo: "bar"
```

The worst part about this is that `foo: "bar"` gets interpreted as a matcher.

**Comment by wenkokke** [comment]
That's deeply confusing.

**Comment by wenkokke** [comment]
Can you confirm you're using the latest version? Can you share the tree?

**Comment by AndreasArvidsson** [comment]
I thought so too. That problem has also been confirmed by pokey

I believe so.

[`"tree-sitter-talon": "github:wenkokke/tree-sitter-talon#fd202684c693d1b893fe34575209452424cc9909"`](https://github.com/cursorless-dev/vscode-parse-tree/blob/226baf3b9abe86fa223defa4334305d60dfb51ed/package.json#L118C1-L118C103)

https://github.com/wenkokke/tree-sitter-talon/commit/fd202684c693d1b893fe34575209452424cc9909

I don't know if I have a good way of getting the entire tree

**Comment by AndreasArvidsson** [comment]
After some more research I've finally figure out that it's not actually language. It's if the right hand value is less than three characters. `ene` is okay but `en` fails.

**Comment by wenkokke** [comment]
Thanks, that's very helpful!

**Comment by wenkokke** [comment]
It's actually _exactly two_. The plus in the definition of implicit string should be a star.

**Comment by AndreasArvidsson** [comment]
I have filed a fix for this
#37
