### ISSUE TITLE
Support Deck 

### ISSUE THREAD

**Issue by Nova38** [wenkokke/tree-sitter-talon#40]
Add support for deck() commands. 

Will come back with some samples, but currently the tree sitter doesn't have a node for dealing with the deck() commands for both the footpetal and the stream deck

**Comment by AndreasArvidsson** [comment]
I'm also interested in this. There are a few examples on Talon search:
https://search.talonvoice.com/search/?q=file%3A.talon%20%5Edeck%5C(&fold_case=auto&regex=true&context=true

**Comment by wenkokke** [comment]
I'm happy to accept aPR. The changes should be very minimal if you follow the example of, e.g., face, and don't try to parse the arguments.

**Comment by AndreasArvidsson** [comment]
Here you go
https://github.com/wenkokke/tree-sitter-talon/pull/55

**Comment by pokey** [comment]
this can be closed, right?

**Comment by AndreasArvidsson** [comment]
Correct
