### ISSUE TITLE
Files with CRLF line endings trigger many parse errors

### ISSUE THREAD

**Issue by wolfmanstout** [wenkokke/tree-sitter-talon#41]
On Windows, the default line ending is CRLF instead of LF. This works fine with Talon, but is not properly parsed by tree-sitter-talon, as discovered in https://github.com/cursorless-dev/cursorless/issues/1950.

The easiest way to reproduce this is to change test/corpus/basic.txt to use CRLF instead of LF line endings (can easily be done with the toggle in VSCode on the bottom right). Rerun tests and you will get many failures.

**Comment by wenkokke** [comment]
The fix in #42 is now published in v4.1.0.
