### ISSUE TITLE
Incorrect parse for context header

### ISSUE THREAD

**Issue by pokey** [wenkokke/tree-sitter-talon#8]
In this code:

https://github.com/wenkokke/tree-sitter-talon/blob/ce869fd826e1be77c5cb40cdf3e7eceee4907d3d/test/corpus/knausj_talon/files.txt#L22623-L22624

It should be parsed as an "and", not an "or", because they are different keys.  It is only an implicit "or" if the keys are the same (eg both `tag` or both `os`)

https://github.com/wenkokke/tree-sitter-talon/blob/ce869fd826e1be77c5cb40cdf3e7eceee4907d3d/test/corpus/knausj_talon/files.txt#L22683

cc/ @rntz

**Comment by pokey** [comment]
Arguably, the parser is trying to do too much here.  The parse should maybe be a bit dumber, and this sort of thing could be determined by clients of the parse tree

**Comment by wenkokke** [comment]
That's fair :) Good catch, I'll simplify the parsing there.
