### ISSUE TITLE
Handle files with no context header

### ISSUE THREAD

**Issue by pokey** [wenkokke/tree-sitter-talon#9]
Could we not just use an [external scanner](https://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners) to emit a phantom `-`-like token of sorts, the way that Python emits whitespace tokens? Is the problem that we'd need to scan the whole file at once?  Maybe could have a heuristic where we look ahead a certain number of chars for a `-`, eg 500KB.  cc/ @rntz

**Comment by wenkokke** [comment]
Unfortunately, tree-sitter doesn't have arbitrary lookahead even in external scanners. If you wanna look past the next character, you either have to skip the current one, e.g., as whitespace, or use it as part of the current token, and there's no going back.

**Comment by rntz** [comment]
It looks like it does have lookahead - see the "advance" and "mark_end" field of the TSLexer struct:

https://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners

So I think what we could do is allow a "phantom dash" token only at the very beginning of document and implement it via this lookahead, by (if the phantom dash is an allowed token) immediately calling mark_end and then advancing until we see a line with just a dash on it or end of file (or exceed 500kb or w/e).

I don't know how well this will interact with incremental parsing, though.

**Comment by rntz** [comment]
Another classic trick for dealing with this kind of ambiguity is to delay resolving it - for instance, GHC handles ambiguity between patterns and expressions by parsing the union of their grammars and checking whether the result was of the expected sort later. Or we could try parsing the intersection of "lines allowed in context header" and "lines allowed in body" until we hit something which is unambiguously one or the other. But tree-sitter doesn't seem to allow post-processing of the parse tree so I'm not sure this would work unless the names of the parse tree nodes for context matches and voice commands were the same...

**Comment by rntz** [comment]
Another classic trick for dealing with this kind of ambiguity is to delay resolving it - for instance, GHC handles ambiguity between patterns and expressions by parsing the union of their grammars and checking whether the result was of the expected sort later. Or we could try parsing the intersection of "lines allowed in context header" and "lines allowed in body" until we hit something which is unambiguously one or the other. But tree-sitter doesn't seem to allow post-processing of the parse tree so I'm not sure this would work unless the names of the parse tree nodes for context headers and voice commands were the same...

**Comment by wenkokke** [comment]
> It looks like it does have lookahead - see the "advance" and "mark_end" field of the TSLexer struct:
> 
> https://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners
> 
> So I think what we could do is allow a "phantom dash" token only at the very beginning of document and implement it via this lookahead, by (if the phantom dash is an allowed token) immediately calling mark_end and then advancing until we see a line with just a dash on it or end of file (or exceed 500kb or w/e).
> 
> I don't know how well this will interact with incremental parsing, though.

It has one character of lookahead. In advance, you must choose whether to add this character to the current token, or to ignore it.

**Comment by wenkokke** [comment]
> Another classic trick for dealing with this kind of ambiguity is to delay resolving it - for instance, GHC handles ambiguity between patterns and expressions by parsing the union of their grammars and checking whether the result was of the expected sort later. Or we could try parsing the intersection of "lines allowed in context header" and "lines allowed in body" until we hit something which is unambiguously one or the other. But tree-sitter doesn't seem to allow post-processing of the parse tree so I'm not sure this would work unless the names of the parse tree nodes for context matches and voice commands were the same...

Yes, the only way that'd work is to unify the AST nodes for match contexts and inline voice commands. Unfortunately, not all match statements are valid voice vommands, due to e.g. the implicit strings.

**Comment by rntz** [comment]
> It has one character of lookahead. In advance, you must choose whether to add this character to the current token, or to ignore it.

The documentation for mark_end explicitly says:

> A function for marking the end of the recognized token. This allows matching tokens that require multiple characters of lookahead. By default (if you don’t call mark_end), any character that you moved past using the advance function will be included in the size of the token. But once you call mark_end, then any later calls to advance will not increase the size of the returned token.

**Comment by wenkokke** [comment]
Ohhh, okay, I can work with this, thanks @rntz!

**Comment by wenkokke** [comment]
For the record, that also fully changes my stance on whether or not to include empty match contexts.
